image: node:20
stages:
  - test

cache:
  key: "$CI_COMMIT_REF_NAME"  # Cache key based on branch or tag
  paths:
    - node_modules/

frontend_format:
  stage: test
  script:
    - cd frontend
    - npm install
    - npx eslint .
    - cd ..

  stage: test
backend_format:
  script:
    - cd backend
    - npm install
    - npx eslint .
    - cd ..

md_test:
  stage: test
  image: python:3.12.9
  before_script:
    - python -m venv env
    - source env/bin/activate
    - pip install pymarkdownlnt
  script:
  - pymarkdown scan .